### ISSUE TITLE
expired token when server time zone is UTC

### ISSUE THREAD

**Issue by elprup** [qiniu/python-sdk#152]
401 response, expired token when local time zone is UTC. If change server time to CST, all is ok.

**Comment by longbai** [comment]
知道了，我看下如何处理

**Comment by longbai** [comment]
time.time()
Return the time in seconds since the epoch as a floating point number. Note that even though the time is always returned as a floating point number, not all systems provide time with a better precision than 1 second. While this function normally returns non-decreasing values, it can return a lower value than a previous call if the system clock has been set back between the two calls.

**Comment by longbai** [comment]
@elprup 我们系统里用的是这个 epoch ，不受时区影响的，所以还是时间没配置对。

**Comment by longbai** [comment]
https://docs.python.org/2/library/time.html
